=== withuno/vault_schema/schemas/8/vault.json
{
  "$id": "https://uno.app/schemas/8/vault.json",
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "title": "Vault",
  "description": "Uno Vault",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "idCardValue": { "type": "string" },
    "vaultSchemaMajor": { "type": "integer" },
    "vaultSchemaMinor": { "type": "integer" },
    "uuid": {
      "type": "string",
      "format": "uuid"
    },
    "email": {
      "type": "string"
    },
    "validatedPhoneNumber": { "type": "string" },
    "name": { "type": "string" },
    "manualItems": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/manualItem"
      }
    },
    "vault": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/vaultItem"
      }
    },
    "privateKeys": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/privateKey"
      }
    },
    "joinedWaitlist": { "type": "boolean" },
    "groups": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/group"
      }
    },
    "contacts": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/contact"
      }
    },
    "confidants": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/contact"
      }
    },
    "friends": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/contact"
      }
    },
    "oldPasswords": {
      "type": "array",
      "items": { "type": "string" }
    },
    "creditCards": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/creditCard"
      }
    },
    "addresses": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/address"
      }
    },
    "notes": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/note"
      }
    },
    "refreshTokens": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/refreshToken"
      }
    },
    "personas": { "type": "array" },
    "travel": { "type": "array" },
    "wifi": { "type": "array" },
    "wiringDetails": { "type": "array" }
  },
  "required": [
    "vaultSchemaMajor",
    "uuid",
    "contacts",
    "confidants",
    "oldPasswords",
    "vault"
  ],
  "$defs": {
    "contact": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "givenName": { "type": "string" },
        "fullName": { "type": "string" },
        "initials": { "type": "string" },
        "phoneNumber": { "type": "string" },
        "state": { "enum": ["denied", "error", "pending", "protecting", "recovery", "removing", "owner", "readonly"] },
        "id": { 
          "type": "string",
          "format": "uuid"
        },
        "share": { "type": "string" },
        "signingKey": { "type": "string" },
        "encryptionKey": { "type": "string" },
        "oldShares": {
          "type": "array",
          "items": { "type": "string" }
        },
        "session": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "seed": { "type": "string" }
          },
          "required": ["seed"]
        }
      },
      "required": ["givenName", "oldShares", "fullName", "initials", "phoneNumber", "id"]
    },
    "refreshToken": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "clientId": { "type": "string" },
        "refreshToken": { "type": "string" }
      },
      "required": ["id", "clientId", "refreshToken"]
    },
    "note": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "schema_type": { "type": "string" },
        "title": { "type": "string" },
        "notes": { "type": "string" }
      },
      "required": ["id", "title", "notes"]
    },
    "address": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "schema_type": { "type": "string" },
        "line1": { "type": "string" },
        "line2": { "type": "string" },
        "city": { "type": "string" },
        "state": { "type": "string" },
        "zip": { "type": "string" },
        "country": { "type": "string" }
      },
      "required": ["id", "line1", "city", "state", "zip", "country"]
    },
    "creditCard": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "schema_type": { "type": "string" },
        "type": { "type": "string" },
        "name": { "type": "string" },
        "holder": { "type": "string" },
        "number": { "type": "string" },
        "expiration": {
          "type": "string",
          "pattern": "^[0,1][0-9]{3}$"
        },
        "cvv": {
          "type": "string"
        },
        "addressUUID": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": ["id", "holder", "expiration"]
    },
    "group": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "seed": { "type": "string" },
        "ownerPublicSigningKey": { "type": "string" }
      },
      "required": ["ownerPublicSigningKey", "seed", "id"]
    },
    "privateKey": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": { "type": "string" },
        "key": { "type": "string" },
        "password": { "type": "string" },
        "walletAddresses": {
          "type": "array",
          "items": { "type": "string" }
        },
        "notes": { "type": "string" },
        "url": { "type": "string" },
        "schema_type": { "type": "string" },
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": ["name", "key", "id"]
    },
    "relatedItem": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "password": { "type": "string" },
        "otpSeed": { "type": "string" }
      }
    },
    "ssoProvider": {
      "type": "object",
      "properties": {
        "default": { "type": "boolean" },
        "provider": { "type": ["string", "null"] },
        "username": { "type": "string" }
      }
    },
    "passkey": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "relyingParty": { "type": "string" },
        "rawKey": { "type": "array", "items": { "type": "integer" } },
        "userName": { "type": "string" },
        "userHandle": { "type": "string" }
      },
      "required": ["id", "relyingParty", "rawKey", "userHandle"]
    },
    "vaultItem": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "schema_type": { "type": "string" },
        "name": { "type": "string" },
        "username": { "type": "string" },
        "password": { "type": "string" },
        "intendedPassword": { "type": "string" },
        "intendedOTPSeed": { "type": "string" },
        "otpSeed": { "type": "string" },
        "notes": { "type": "string" },
        "relatedItems": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/relatedItem"
          }
        },
        "passkeys": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/passkey"
          }
        },
        "ssoProvider": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ssoProvider"
          }
        }
      },
      "required": ["id", "name"]
    },
    "manualItem": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "schema_type": { "type": "string" },
        "matching_hosts": { "type": "array", "items": { "type": "string" } },
        "name": { "type": "string" },
        "url": { "type": "string" },
        "username": { "type": ["string", "null"] },
        "password": { "type": ["string", "null"] },
        "intendedPassword": { "type": "string" },
        "otpSeed": { "type": ["string", "null"] },
        "notes": { "type": "string" },
        "ssoProvider": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ssoProvider"
          }
        },
        "passkeys": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/passkey"
          }
        },
        "relatedItems": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/relatedItem"
          }
        }
      },
      "required": ["id"]
    }
  }
}

=== withuno/vault_schema/test/with_schema_types.json
{
	"idCardValue": "SBr95SOWftis4FL8p1Y2eZZo3+5V9XWh+3ipsU8J0xY=",
	"vaultSchemaMinor": 0,
	"vaultSchemaMajor": 7,
	"uuid": "e7d0e72f-4aee-4abd-92b6-a14934792776",
	"email": "chris+624@uno.app",
	"vault": [],
	"manualItems": [
		{
			"name": "asdasd",
			"url": "gngmememhijbokakblbhgfhagjdjcfjo",
			"username": "asdasd",
			"password": "asdasdsd",
			"notes": "",
			"id": "59d7753b-cda7-4086-b144-2d4b98f718a8",
			"relatedItems": [],
			"ssoProvider": [],
			"matching_hosts": [
				"gngmememhijbokakblbhgfhagjdjcfjo"
			]
		}
	],
	"contacts": [],
	"confidants": [],
	"oldPasswords": [],
	"privateKeys": [
		{
			"key": "key",
			"password": "password",
			"walletAddresses": [
				"01231231"
			],
			"name": "title2",
			"notes": "12313123123123",
			"url": "13123123",
			"id": "a3a1af31-bbfa-46ec-b124-f2cd57116b6a",
			"schema_type": "private_key"
		}
	],
	"notes": [
		{
			"title": "asdasdas",
			"notes": "asdasdasd",
			"id": "9a7737af-9732-41ed-96e8-412b19d7def1",
			"schema_type": "secure_note"
		}
	],
	"creditCards": [
		{
			"type": "unknown",
			"name": "123123312123asdasd",
			"holder": "asdads",
			"number": "1234123441231231",
			"expiration": "0930",
			"cvv": "111",
			"id": "fd77749f-ec6f-456e-bdcf-2eaedeeeccff",
			"schema_type": "credit_card"
		}
	],
	"addresses": [
		{
			"line1": "123",
			"line2": "asdads",
			"city": "adsads",
			"state": "PA",
			"zip": "10001",
			"country": "US",
			"id": "efb3c1b9-f79b-4b07-a5cd-00c6ed80f638",
			"schema_type": "address"
		}
	]
}

=== withuno/vault_schema/test/with_no_id_card_value.json
{
	"uuid": "666CFC96-2826-4F83-998B-E704424E52CB",
	"name": "Standard",
	"vault": [],
	"addresses": [],
	"wiringDetails": [],
	"manualItems": [
		{
			"username": "appledapple",
			"password": "3798437y9f3y9fy83y38",
			"id": "219B7A7A-727E-4014-B336-3ED86766E1CB",
			"notes": "NICE OK",
			"url": "Facebook",
			"relatedItems": [
				{
					"password": "aplpeOK"
				},
				{
					"password": "9798798789"
				},
				{
					"password": "r68f68df86f8d86df8f68d"
				},
				{
					"password": "g8dg34f874g3f8g348f"
				},
				{
					"password": "fg9734gcf7r4bf79ey"
				}
			]
		},
		{
			"username": "a@b.com",
			"password": "hfoiehiofh3oihfoiw",
			"id": "767ECC8E-C3AB-4F28-91EC-36B41DC1438B",
			"notes": "OK",
			"url": "twitter.com",
			"relatedItems": []
		},
		{
			"relatedItems": [],
			"password": "bku/Bc/~z2GY^w <UnJ'Ji]d7+k;g6IV;GC[",
			"id": "99031C44-8D22-4AFC-B95F-7B45E96CCA9F",
			"notes": "OK",
			"username": "a@b.com",
			"name": "Facebook",
			"url": "https://www.facebook.com"
		},
		{
			"relatedItems": [
				{
					"password": "12345"
				},
				{
					"password": "1234580890"
				}
			],
			"password": "1234580890880",
			"id": "234E3A0F-1FAA-423A-A58C-B8C56D947F35",
			"notes": "OKII",
			"username": "bleepyboo22",
			"name": "Apple",
			"url": "www.apple.com"
		}
	],
	"refreshTokens": [],
	"privateKeys": [
		{
			"password": "",
			"id": "592D8A57-8ECA-4854-B82D-864938CF4FF0",
			"notes": "",
			"walletAddresses": [],
			"key": "4EI7/mtejl7qxb2LA2QjAiajMkvO3Q70FPYKWkeedW0=",
			"name": "TGR",
			"url": ""
		}
	],
	"notes": [],
	"wifi": [],
	"personas": [],
	"travel": [],
	"contacts": [],
	"oldPasswords": [
		"fakePWdropbox"
	],
	"confidants": [],
	"friends": [
		{
			"phoneNumber": "789779798",
			"id": "0AC34321-A485-4C4D-8D01-DCDE3FD9FFCA",
			"fullName": "Bob Barker",
			"oldShares": [],
			"session": {
				"seed": "ZWNgOCwfqYEfPg=="
			},
			"givenName": "Bob",
			"state": "readonly",
			"initials": "BB"
		},
		{
			"phoneNumber": "89890878978",
			"id": "D9DB1187-620B-465A-87FD-848D172B3D50",
			"fullName": "Tiegr T",
			"oldShares": [],
			"session": {
				"seed": "MvBwukQ8G0l7aw=="
			},
			"givenName": "Tiegr",
			"state": "readonly",
			"initials": "T "
		}
	],
	"groups": [
		{
			"id": "1EE65F54-8A55-433B-8C85-9934781867E4",
			"seed": "KL4Fa/kSqS0BxLqcb5rF0JJBN/dtOPWcdL/5X2IVutI=",
			"ownerPublicSigningKey": "w20HP9B+qgBpByM5azkZU/ek44LsnDFVaA202MwEU1c="
		}
	],
	"creditCards": [],
	"vaultSchemaMajor": 7
}
